academy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^conference/', include('conferences.urls', namespace='conference')),
    url(r'^news/', include('academy_news.urls', namespace='news')),
    url(r'^robosprint/', include('robosprint.urls', namespace='robosprint')),
    url(r'^', include('main_app.urls', namespace='main')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

academy_news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.NewsListView.as_view(), name='news'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.NewsDetailView.as_view(), name='news_detail'),

]

templates/main/contacts.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	- Контакти
{% endblock title %}

{% block content %}
<div class="container">
	<div class="static_page">
		<h3>Контакти</h3>
		<p>Ви можете зв'язатися з нами за телефоном або електронною адресою.<br>
		Дзвоніть або пишіть, Вам завжди раді!</p>
        {% for contact in contacts %}
            <address>Адреса: {{ contact.address }}</address>
            {% for phone in contact.phones.all %}
                <p><img src="{{ phone.provider.url }}" height="30" width="30">
                    {{ phone.number }}
                </p>
            {% endfor %}
            {% for email in contact.emails.all %}
                <p>e-mail: {{ email }}</p>
            {% endfor %}
		{% endfor %}
	</div>
</div>

{% endblock content %}

templates/main/main.html
{% extends 'base.html' %}

{% load static %}


{% block jumbo %}
    <div class="jumbotron">
        <div class="container">
          <h2>Академія технічних наук України (АТНУ)</h2>
            <article>Наукова громадська організація, що об'єднує вчених-теоретиків та практиків у галузі технічних наук.<br/>
                    Заснована 30 листопада 2016 р. в Івано-Франківську.<br/>
                    Академія технічних наук України є громадським науковим, методичним і координаційним центром України
                    у сфері технічних наук.<br/>
                    Мета діяльності – цілеспрямований розвиток технічних наук, захист фахових інтересів,
                    координація науково-дослідної роботи, обмін досвідом.
            </article>
        </div>
    </div>
{% endblock jumbo %}

{% block content %}


    <div class="container">
        <h4 style="text-align:center; color: #265">ОСТАННІ НОВИНИ</h4>
        <div class="news">
        {% for n in news %}
            <h4>{{ n.title }}</h4>
            <h6>{{ n.date_created }}</h6>
            <p>{{ n.annotation|safe }}</p>
            <p><a href="{% url "news:news_detail" n.id n.slug %}">Читати далі...</a> </p>
            <hr>
        {% endfor %}
        </div>
    </div>
{% endblock content %}