academy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^conference/', include('conferences.urls', namespace='conference')),
    url(r'^news/', include('academy_news.urls', namespace='news')),
    url(r'^robosprint/', include('robosprint.urls', namespace='robosprint')),
    url(r'^', include('main_app.urls', namespace='main')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

conferences/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^(?P<id>\d+)-(?P<slug>[-\w]+)/theses/$', views.thesis_list, name='thesis_list'),
    url(r'^(?P<id>\d+)-(?P<slug>[-\w]+)/$', views.conference_detail, name='conference_detail'),
    url(r'^$', views.conference_list, name='conference_list'),
]

main_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^contacts/$', views.contacts, name='contacts')
]

templates/conference_app/conference_detail.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
        <link rel="stylesheet" href="{% static 'css/conf.css' %}">
{% endblock extra_css %}
{% block title %} - {{ conference.get_number_of_conference }} {{conference.title }}{% endblock title %}
{% block content %}
    <div class="container">
        <ol class="breadcrumb">
              <li><a href="{% url 'main:main' %}">Головна</a></li>
              <li><a href="{% url 'conference:conference_list' %}">Конференції</a></li>
              <li class="active">{{ conference.title }} : {{ conference.date_start|date:"d b Y"}}</li>
        </ol>
            <div class="conference_detail">
                <h4 id="conf-title">{{ conference.title }} / {% if conference.title_eng %}{{ conference.title_eng }}{% endif %}</h4>
                <h5 style="text-align: center">{{ conference.level|upper }} КОНФЕРЕНЦІЯ</h5>
                <p><strong>Місце проведення:</strong> {{ conference.place }}</p>
                <p><strong>Дата проведення:</strong> {{ conference.date_start }} - {{ conference.date_end }}</p>
                <p>{% if conference.status %}Прийняло участь{% else %}Зареєстровано{% endif %}
                    <strong>{{ conference.get_number_of_participants }}</strong> {{ participant_message }} </p>
                <p>{% if conference.status %}Заслухано{% else %}Зареєстровано{% endif %}
                    <strong>{{ conference.get_number_of_thesises }}</strong> {{ thesis_message }}
                    <a href="{% url "conference:thesis_list" conference.id conference.slug %}">Переглянути</a>
                </p>
                {% if conference.information_message %}
                    <p><a href="{{ conference.information_message.url }}">Інформаційне повідомлення</a></p>
                {% endif %}
                {% if conference.thesises_file %}
                    <p><a href="{{ conference.thesises_file.url }}">Завантажити збірку доповідей</a></p>
                {% endif %}
            </div>
    </div>
{% endblock content %}

templates/conference_app/conference_list.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
        <link rel="stylesheet" href="{% static 'css/conf.css' %}">
{% endblock extra_css %}
{% block title %} - Конференції{% endblock title %}
{% block content %}
    <div class="container">
        {% for conference in conferences %}
            <div class="col-xs-12">
                <div class="conference_short">
                    <h4 id="conf-title">{{ conference.title }}{% if conference.title_eng %} / {{ conference.title_eng}}{% endif %}</h4>
                    <p>{{ conference.level|upper }} КОНФЕРЕНЦІЯ</p>
                    <p><strong>Місце проведення:</strong> {{ conference.place }}</p>
                    <p><strong>Дата проведення:</strong> {{ conference.date_start }} - {{ conference.date_end }}</p>
                    <p><a href="{{ conference.get_absolute_url }}">Детальніше...</a></p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}
{% block pagination %}
    {% if is_paginated %}
        {% with object_list=conferences %}
        <div class="paginator">
            {% include "pagination.html" %}
        </div>
        {% endwith %}
    {% endif %}
{% endblock pagination %}

templates/conference_app/thesis_list.html
{% extends 'base.html' %}

{% load static %}
{% load modify_query %}

{% block extra_css %}
        <link rel="stylesheet" href="{% static 'css/conf.css' %}">
{% endblock extra_css %}
{% block title %} - {{ conference.get_number_of_conference }} {{conference.title }} - Доповіді{% endblock title %}
{% block content %}
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'main:main' %}">Головна</a></li>
            <li><a href="{% url 'conference:conference_list' %}">Конференції</a></li>
            <li>
                <a href="{% url "conference:conference_detail" conference.id conference.slug %}">
                    {{ conference.title }} : {{ conference.date_start|date:"d b Y"}}
                </a>
            </li>
            <li class="active">
                {% if q %}
                    <a href="{% url "conference:thesis_list" conference.id conference.slug %}">Тези</a>
                {% elif not q %}
                    Тези
                {% endif %}
            </li>
            {% if q %}<li class="active">Результати пошуку</li>{% endif %}
        </ol>
            <div class="conference_detail">
               <div class="conference_detail">
                    <h4 id="conf-title">{{ conference.title }}{% if conference.title_eng %} / {{ conference.title_eng }}{% endif %}</h4>
                    <h5 style="text-align: center">{{ conference.level|upper }} КОНФЕРЕНЦІЯ</h5>
                        <h5 style="text-align: center">Доповіді</h5>

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                <form class="form-inline search" action="{% url "conference:thesis_list" conference.id conference.slug %}" method="get">
                                    {{ search_form.q }}
                                    <input type="submit" class="btn btn-primary search-btn" value="Пошук">
                                </form>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                <form class="form-inline">
                                    {{ form.as_p }}
                                </form>
				            </div>
       	                </div>
                        <div class="row">
                            <div class="col-xs-12">
                                {% if q %}
                                    <p class="search_results">За Вашим запитом <strong>"{{ q }}"</strong> знайдено <strong>{{ number_of_search_results }}</strong> {{ thesis_message }}</p>
                                {% endif %}
                            </div>
                        </div>

                        <table class="table table-striped table-hover">
                               <tbody>
                               {% for thesis in theses %}
                                    <tr>
                                       <td>
                                           <a href="{{ thesis.thesis.url }}" target="_blank"> <strong>{{ thesis.title }}</strong></a>
                                           <p><small>{{ thesis.section }}</small></p>
                                           <p>{{ thesis.get_authors }}</p>
                                       </td>
                                    </tr>
                                {% endfor %}
                               </tbody>
                        </table>
                </div>
            </div>
    </div>
{% endblock content %}
{% block pagination %}
    {% if is_paginated %}
        {% with object_list=theses %}
        <div class="paginator">
            {% include "pagination.html" %}
        </div>
        {% endwith %}
    {% endif %}
{% endblock pagination %}