academy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^conference/', include('conferences.urls', namespace='conference')),
    url(r'^news/', include('academy_news.urls', namespace='news')),
    url(r'^robosprint/', include('robosprint.urls', namespace='robosprint')),
    url(r'^', include('main_app.urls', namespace='main')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

academy_news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.NewsListView.as_view(), name='news'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.NewsDetailView.as_view(), name='news_detail'),

]

conferences/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^(?P<id>\d+)-(?P<slug>[-\w]+)/theses/$', views.thesis_list, name='thesis_list'),
    url(r'^(?P<id>\d+)-(?P<slug>[-\w]+)/$', views.conference_detail, name='conference_detail'),
    url(r'^$', views.conference_list, name='conference_list'),
]

main_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^contacts/$', views.contacts, name='contacts')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
     <script async src="https://www.googletagmanager.com/gtag/js?id=UA-124907141-1"></script>
     <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'UA-124907141-1');
     </script>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Академія технічних наук України: організація конференції
                    'Прикладні науково-технічні дослідження', випуск колективних монографій, фахова співпраця вчених у сфері 
                    технічних наук ">
	<meta name="keywords" content="прикладні науково-технічні дослідження, технічні науки, колективні монографії, співпраця вчених">
	<title>Академія технічних наук України{% block title %}{% endblock title %}</title>
	<link rel="shortcut icon" href="{% static "img/favicon.png" %}" type="image/png" />
	<link href="https://fonts.googleapis.com/css?family=Open+Sans&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% block extra_css %}{% endblock extra_css %}
</head>
<body>

	<!-- Header -->
		<header>
			<nav class="navbar navbar-default navbar-fixed-top menu ">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                          data-target="#menu-collapse" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="{% url 'main:main' %}"><img src="{% static "img/logo_academy.png" %}"></a>
			    </div>
			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="menu-collapse">
                    <ul class="nav navbar-nav">
                    {% url 'main:main' as index %}
                        <li {% if request.path == index %}class="active menu_item menu_item--current"{% else %}
                            class="menu_item"{% endif %}>
                            <a class="menu_link" href="{% url "main:main" %}">Головна<span class="sr-only">(current)</span></a>
                        </li>
                        <li {% if  'news/' in request.path %}class="active menu_item menu_item--current"{% else %}
                            class="menu_item"{% endif %}>
                            <a class="menu_link" href="{% url 'news:news' %}">Новини</a>
                        </li>
                        <li {% if  'conference/' in request.path %}class="active menu_item menu_item--current"{% else %}
                            class="menu_item"{% endif %}>
                            <a class="menu_link" href="{% url 'conference:conference_list' %}">Конференції</a>
                        </li>
						<li {% if  'robosprint/' in request.path %}class="active menu_item menu_item--current"{% else %}
                            class="menu_item"{% endif %}>
                            <a class="menu_link" href="{% url 'robosprint:main' %}">RoboSprint</a>
                        </li>
                        <li {% if 'contacts' in request.path %}class="active menu_item menu_item--current"{% else %}
                            class="menu_item"{% endif %}>
                            <a class="menu_link" href="{% url "main:contacts" %}">Контакти</a>
                        </li>

                    </ul>
   			    </div><!-- /.navbar-collapse -->
			   </div><!-- /.container -->
			</nav>
		</header>
	<!-- Main Block -->
		<main>
            {% block jumbo %}
            {% endblock jumbo %}
			{% block content %}
			{% endblock content %}
			<!--Footer-->

			<footer>
			{% block pagination %}
			{% endblock pagination %}
				<div class="main-footer">
					<div class="container">
						<div class="col-xs-12 col-sm-12 col-md-12 copyright">
							<p>&copy; 2018 Академія технічних наук України</p>
						</div>
					</div>
				</div>
			</footer>
		</main>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
	<script src="{% static 'js/main.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/pagination.html
{# 		 load modify_query %} #}
        <ul class="pagination">
			<li>
				{% if object_list.has_previous %}
					<a href="?page={{ object_list.previous_page_number  }}{% if q %}&q={{ q }}{% endif %}{% if section %}&section={{ section }}{% endif %}">
							&laquo;
					</a>
				{% else %}
					<li><span>&laquo;</span></li>
				{% endif %}
			</li>
				{% for i in page_range %}
					{% if i == DOT %}
						<li><span>...</span></li>
					{% elif i == object_list.number %}
						<li class="active"><span>{{ i }}</span></li>
					{% else %}
						<li>
							<a href="?page={{ i }}{% if q %}&q={{ q }}{% endif %}{% if section %}&section={{ section }}{% endif %}">
								{{ i }}
							</a>
						</li>
					{% endif%}
				{% endfor %}
			<li>
				{% if object_list.has_next %}
					<a href="?page={{ object_list.next_page_number }}{% if q %}&q={{ q }}{% endif %}{% if section %}&section={{ section }}{% endif %}">
						&raquo;
					</a>
				{% else %}
					<li><span>&raquo;</span></li>
				{% endif %}
			</li>
		</ul>